- lib/fog/google/compute.rb
- lib/fog/google/core.rb
- lib/fog/google/dns.rb
- lib/fog/google/monitoring.rb
- lib/fog/google/sql.rb
- tests/google/credentials_tests.rb
As discussed per fog/fog#3461 pulling changes over.
> JSON Credentials

- lib/fog/bin/google.rb
Forgot to move the bin file.
cc/ @icco @erjohnso @ihmccreery
> Add Fog Binary for Google

- CONTRIBUTING.md
> CONTRIBUTING.md points to fog/CONTRIBUTING.md

- fog-google.gemspec
- lib/fog/google.rb
I discovered these bugs while rewriting tests.
> Fixups for `fog-google` extraction

- lib/fog/google/models/compute/images.rb
Revert logic from fog/fog@39188c331cbe5e51169f5dcd12694a998f5502ba, make it consistent with desired functionality; closes #20.
@plribeiro3000 Can you please review?
> Repair rescue logic for get images

- lib/fog/google/models/compute/server.rb
Fixing #36. Adding gcloud compute aliases support to be consistent with official utility.
> Adding support for gcloud scope aliases

- CONTRIBUTING.md
@plribeiro3000 @erjohnso Can you two have a look at this and make sure it's comprehensible?  Am I missing anything?
> Add explanation of transition from Shindo to Minitest in CONTRIBUTING

- lib/fog/google/models/compute/server.rb
- lib/fog/google/requests/compute/insert_server.rb
- lib/fog/google/requests/compute/set_server_scheduling.rb
https://cloud.google.com/compute/docs/instances/preemptible
> added preemptible

- lib/fog/google/models/compute/images.rb
Subject says it all.
/cc: @erjohnso, @temikus
> Added Windows image project; fixed docs URL.

- examples/dns/zones.rb
> Fixing zones example

- lib/fog/google/models/storage/directory.rb
- lib/fog/google/requests/storage/put_bucket.rb
> add :storage_class attribute for NEARLINE

- lib/fog/google/models/compute/servers.rb
Tiny PR to keep the bootstrap method current.
> Updating bootstrap method

- lib/fog/google/version.rb
- lib/fog/storage/google_xml/real.rb
Fixes #121. 
Any thoughts on how to test?
> Broken signing for GCS XML

- lib/fog/google/version.rb
I'm planning to release 0.3.2 with my changes to unblock #124 
@icco @plribeiro3000 - are you ok with it?
> Releasing 0.3.2

- lib/fog/storage/google_json/real.rb
I strongly suspect that https://github.com/fog/fog-google/pull/111 broke JSON signature as well.
Reverted as with #122 
/CC @icco @plribeiro3000 can you please verify?
> Reverting StorageJSON signature

- test/integration/compute/test_servers.rb
- test/integration/storage/test_buckets.rb
- test/integration/storage/test_directories.rb
- test/integration/storage/test_objects.rb
See individual commits for independent changes.
> More fixed warnings

- test/integration/compute/test_regions.rb
Simple enough; just updates a failing test
> Remove non-existant regions and add existing ones

- lib/fog/compute/google/models/server.rb
- lib/fog/compute/google/models/target_pool.rb
- lib/fog/compute/google/requests/get_target_pool_health.rb
WIP for #162 Do not merge yet.
@selmanj PTAL, did you have something like this in mind?
> Add ability to check single instance health

- lib/fog/compute/google/mock.rb
- lib/fog/compute/google/models/server.rb
- lib/fog/compute/google/requests/insert_server.rb
- test/unit/compute/test_server.rb
> Use nondeprecated ssh keys

- lib/fog/google/shared.rb
Also reformatted up the yard doc while documenting the additional parameter
> Pass google client options to the correct client

- lib/fog/storage/google_json/models/files.rb
- lib/fog/storage/google_json/requests/get_bucket.rb
This should fix #206. @MarcelHB, could you verify this fixes your bug? @Temikus mind giving a quick review?
> IsTruncated doesn't work in json storage api

- lib/fog/compute/google.rb
- lib/fog/compute/google/models/firewall.rb
- lib/fog/compute/google/requests/update_firewall.rb
this commit allows one to update the firewall rules
> add support for update_firewall

- lib/fog/compute/google/models/snapshots.rb
- test/integration/compute/test_snapshots.rb
Fixes #239 
I added a bare-bones test, obviously I don't think this is sufficiently testing snapshot functionality but I figured something is better than nothing.
/cc @agrare
> Check for empty snapshots when listing

- lib/fog/compute/google/models/backend_service.rb
- lib/fog/compute/google/models/backend_services.rb
- lib/fog/compute/google/requests/add_backend_service_backends.rb
- lib/fog/compute/google/requests/delete_backend_service.rb
- lib/fog/compute/google/requests/get_backend_service.rb
- lib/fog/compute/google/requests/get_backend_service_health.rb
- lib/fog/compute/google/requests/insert_backend_service.rb
- lib/fog/compute/google/requests/list_backend_services.rb
@icco I'll need your help with the tests. This https://github.com/fog/fog-google/blob/master/test/integration/factories/backend_services_factory.rb#L17 seems to be failing with `NoMethodError: undefined method `http_health_checks' for #<Google::Apis::ComputeV1::ComputeService:0x0055b5c85dbc80>` Should I just remove this param and the http health checks factory?
> Upgrade google client backend services

- lib/fog/google/models/sql/flag.rb
- lib/fog/google/models/sql/flags.rb
- lib/fog/google/models/sql/tier.rb
- lib/fog/google/models/sql/tiers.rb
- lib/fog/google/requests/sql/list_flags.rb
- lib/fog/google/requests/sql/list_tiers.rb
- lib/fog/google/sql/real.rb
- test/integration/sql/test_flags.rb
- test/integration/sql/test_tiers.rb
Part 1: 
- Update SQL client to use new google api client.
- Updated: flags, tiers
Resources TODO (all involving instances, which is the largest chunk):
- instances
- operations
- ssl_certs
- backup_runs
> Part 1 of Cloud SQL upgrade

- lib/fog/compute/google/models/zone.rb
- lib/fog/compute/google/models/zones.rb
- lib/fog/compute/google/requests/get_zone.rb
- lib/fog/compute/google/requests/list_zones.rb
Mostly an update for Zone model.
> Upgrade Compute zones

- lib/fog/compute/google.rb
- lib/fog/compute/google/models/machine_type.rb
- lib/fog/compute/google/models/machine_types.rb
- lib/fog/compute/google/requests/get_machine_type.rb
- lib/fog/compute/google/requests/list_aggregated_machine_types.rb
- lib/fog/compute/google/requests/list_machine_types.rb
> Upgrade machine type requests

- lib/fog/compute/google/models/network.rb
- lib/fog/compute/google/models/networks.rb
- lib/fog/compute/google/requests/delete_network.rb
- lib/fog/compute/google/requests/get_network.rb
- lib/fog/compute/google/requests/insert_network.rb
- lib/fog/compute/google/requests/list_networks.rb
I'll probably hold off on adding new requests until we have everything else updated.
> Upgrade existing Compute networks models & requests

- lib/fog/compute/google.rb
- lib/fog/compute/google/models/global_address.rb
- lib/fog/compute/google/models/global_addresses.rb
- lib/fog/compute/google/requests/delete_global_address.rb
- lib/fog/compute/google/requests/get_global_address.rb
- lib/fog/compute/google/requests/insert_global_address.rb
- lib/fog/compute/google/requests/list_global_addresses.rb
@icco It doesn't look like I have permissions to request a review (no button in the sidebar)
> Upgrade global addresses and add list request

- lib/fog/compute/google/requests/delete_global_operation.rb
- lib/fog/compute/google/requests/delete_region_operation.rb
- lib/fog/compute/google/requests/delete_zone_operation.rb
- lib/fog/compute/google/requests/get_global_operation.rb
- lib/fog/compute/google/requests/get_region_operation.rb
- lib/fog/compute/google/requests/get_zone_operation.rb
- lib/fog/compute/google/requests/list_global_operations.rb
- lib/fog/compute/google/requests/list_region_operations.rb
- lib/fog/compute/google/requests/list_zone_operations.rb
Model is shared operation model
> Upgrade region, zone, and global operation requests

- lib/fog/google/models/monitoring/metric_descriptors.rb
- lib/fog/google/models/monitoring/monitored_resource_descriptors.rb
- lib/fog/google/models/pubsub/subscriptions.rb
- lib/fog/google/models/pubsub/topics.rb
- lib/fog/google/models/sql/backup_runs.rb
- lib/fog/google/models/sql/instances.rb
- lib/fog/google/models/sql/operations.rb
- lib/fog/google/models/sql/ssl_certs.rb
These are all the models that don't require extra work/conflict with other PRs.
> Fix error handling for 404 responses for monitoring, pub/sub, sql

- lib/fog/storage/google_json/requests/get_object.rb
Fixes #291 
tbh the 'streaming' part could be improved but this will work for now
> Add block back into storage get_object

- lib/fog/storage/google_json/models/files.rb
for #291 
cc @tcdowney + @emilymye
> Readd files.head as an alias to metadata

- lib/fog/storage/google_json/models/files.rb
Fixes syntax error for files#head alias
Thanks!
Tim && @ericpromislow
> Fix GoogleJson files#head alias

- CONTRIBUTORS.md
- LICENSE.md
- fog-google.gemspec
> Update Contributors and License

- lib/fog/storage/google_json/models/directories.rb
- lib/fog/storage/google_json/models/directory.rb
- lib/fog/storage/google_json/models/files.rb
- lib/fog/storage/google_json/requests/list_objects.rb
Fixes #296 
@icco The issue above was re-opened since it wasn't actually resolved. Could we possibly get a new release for this asap after @tcdowney confirms?
> Fix arguments for storage list_objects and enable :prefix

- lib/fog/compute/google/models/instance_group.rb
Adding add_instance back to the model, seems I forgot to port it
from the collection earlier.
Fixes #308
> Fixing add_instance method

- examples/storage_json.rb
https://github.com/fog/fog-google/blob/master/lib/fog/storage/google_json/requests/put_bucket.rb#L18
> Fixed example with `predefined_acl`

- lib/fog/compute/google/models/server.rb
> Add .public_ip_address helper

- CONTRIBUTING.md
- README.md
This is a WIP PR to hopefully fix flaky disk tests. I'll see if I can reproduce the behaviour with the same test seed.
> Fixing test docs

- lib/fog/compute/google/models/servers.rb
- lib/fog/compute/google/models/target_pool.rb
- test/integration/compute/test_target_pools.rb
To prevent #346 from re-occurring.
> Target pool health test

- test/integration/compute/test_instance_group_managers.rb
- test/integration/compute/test_instance_templates.rb
- test/integration/factories/instance_group_manager_factory.rb
- test/integration/factories/instance_template_factory.rb
> Add IGM/InstanceTemplate tests

- CHANGELOG.md
- lib/fog/google/version.rb
This release is going out the door faster than expected due to #356 
Huge thanks to our contributors: @bpaquet @tumido 🎆🎆🎆
> Release 1.5.0 🚀

- test/integration/monitoring/test_timeseries.rb
As it turns out Stackdriver changes their error messages, so just retrying on client errors.
This is not as critical now to fail fast after I parallelised the CI.
> Removing retry regex

- lib/fog/compute/google/models/server.rb
implementing #217 you also have pull request for vagrant-google https://github.com/mitchellh/vagrant-google/pull/203
> Added option for network ip

- CHANGELOG.md
- lib/fog/google/version.rb
Huge thanks to all our contributors 🎆 
Special thanks to: @mattimatti, @miwelc
CC: @icco
> Release 1.6.0 🚀

- .codecov.yml
- test/integration/compute/test_global_addresses.rb
- test/integration/factories/global_addresses_factory.rb
To verify whether the coverage delta is done properly, I'm adding more tests for a previously untested resource. Let's see if there's any delta.
Bonus: more tests \o/
> Add global addresses tests

- CHANGELOG.md
- CONTRIBUTING.md
- Gemfile
- README.md
We can do a better job documenting our code.
This is a PR to add tools to help us track it.
> Add doc coverage tracking

- README.md
> Remove CodeClimate

- test/integration/compute/test_zones.rb
This is also to test coverage integration.
> Adding zone collection tests

- README.md
> Fix broken MIGRATING.md link

- examples/create_instance.rb
- test/integration/compute/test_addresses.rb
- test/integration/compute/test_networks.rb
- test/integration/factories/collection_factory.rb
Need to make some changes to the collection factory to make resource creation easier.
> More tests + improve helpers

- README.md
@icco - PTAL the wording, want to make sure it sounds fair.
Fixes #407
> Update supported ruby versions

- CHANGELOG.md
- lib/fog/google/version.rb
Special thanks to: @stanhu, @dosuken123 and @mkozono
CC: @icco
> Release 1.7.0 🚀 

- CHANGELOG.md
- lib/fog/google/version.rb
This is a hotfix release.
Special thanks to @stanhu for contributing the patch!
CC: @icco
> Release 1.7.1 🛠 

- test/integration/compute/core_compute/test_client_options.rb
> Add a simple test for client options

- CHANGELOG.md
- lib/fog/google/version.rb
Special thanks to: @AlexanderZagaynov
CC: @icco
> Release 180 🚀

- fog-google.gemspec
it follows SemVer https://github.com/fog/fog-json#versioning
> relax fog-json constraint

- CHANGELOG.md
- lib/fog/google/version.rb
Special thanks to: @itopalov @pravi
CC: @icco
> Release 1.8.2 🛠

- CHANGELOG.md
- README.md
- lib/fog/google/version.rb
Special thanks to: @mavin
CC: @icco
> Release 1.9.0 🚀

- tasks/changelog.rake
Called via `rake changelog:generate`
> Add a helper rake task to populate changelog

- CHANGELOG.md
- lib/fog/google/version.rb
Special thanks to: @mavin 
CC: @icco
> Release 1.9.1 🛠 

- README.md
I think it's a good idea since the service is now free. This'll keep us on our toes dep-wize.
I also added the proper label config so it'll automatically try to integrate changes.
@icco WDYT?
> Add dependabot

- lib/fog/compute/google/models/disk.rb
- lib/fog/compute/google/requests/insert_disk.rb
Closes #374 
Also added the users attribute to disks in the PR (https://cloud.google.com/compute/docs/reference/rest/v1/disks#resource-disk)
> Add labels parameter to disk creation

- CHANGELOG.md
- lib/fog/google/version.rb
Special thanks to: @icco,  dvanbrug@, gscho@, kgaikwad@, militarpancho@
CC: @icco
> Release 1.10.0 🚀

- lib/fog/storage/google_xml/requests/head_object.rb
- test/integration/sql/test_certs.rb
To bring it into conformance with the rest of the methods, e.g. GET, PUT, DELETE
Fixes #416
> Add :idempotent flag to Storage XML HEAD Object

- CHANGELOG.md
- lib/fog/google/version.rb
Special thanks to: @simonschellaert, @chvreddy and @frankyn
CC: @icco
> Release 1.11.0 🚀

- CHANGELOG.md
- lib/fog/google/version.rb
Special thanks to: @lcy0321, @stanhu, @gogainda
CC: @icco
> Release 1.12.0 🚀

- CHANGELOG.md
- lib/fog/google/version.rb
- tasks/changelog.rake
Special thanks to: @nageshlop @yosiat
CC: @icco
> Release 1.12.1 🛠

- CHANGELOG.md
- lib/fog/google/version.rb
Special thanks to: @deeeki @geemus @krokodaxl @mshibuya @stanhu
/CC @icco
> Release 1.14.0

- CHANGELOG.md
- lib/fog/google/version.rb
Special thanks to: @gogainda
CC @icco
> Release 1.16 🚀

- CHANGELOG.md
- lib/fog/google/version.rb
Special thanks to: @stanhu @kbrock 
> Release 1.16.1

- CHANGELOG.md
- lib/fog/google/version.rb
> Release 1.17.0

- lib/fog/compute/google/models/images.rb
as returned by
`gcloud compute images list | cut -c55-75 \
| grep -v PROJECT | sort | uniq`
> Update to the current images projects list

- README.md
See: https://github.com/dependabot/feedback/issues/6
> Update dependabot badge

- README.md
- examples/create_instance.rb
- examples/create_instance_with_attached_disk.rb
- examples/get_list_images.rb
- examples/load-balance.rb
- examples/metadata.rb
- examples/network.rb
- lib/fog/compute/google/models/server.rb
- lib/fog/compute/google/models/servers.rb
- lib/fog/compute/google/requests/insert_server.rb
- test/helpers/integration_test_helper.rb
Mainly fixing failing tests due to expired images and image families.
> Update deprecated images & image families

- fog-google.gemspec
Upgrading Google Library dependencies across the board, it's been a while so will wait for a full integration test roll.
> Upgrade google client library dependencies

- fog-google.gemspec
- lib/fog/storage/google_json/utils.rb
- test/unit/storage/test_json_requests.rb
This fixes https://github.com/fog/fog-google/issues/590.
> Generate URIs using Addressable

- CHANGELOG.md
- lib/fog/google/version.rb
> Release 1.22.0

- CHANGELOG.md
- lib/fog/google/version.rb
> Release 1.24.0 🚀 

- CHANGELOG.md
- lib/fog/google/version.rb
> Release 1.24.1
