fog/fog-google

lib/fog/google/compute.rb, lib/fog/google/models/compute/images.rb
Added the option for setting extra global projects during initialization.
My previous approach did not fully work if you want to rely on these extra global projects for disk creation for example. https://github.com/fog/fog-google/pull/29
=> google_extra_global_projects on initialization for compute

examples/launch_micro_instance.rb
As written, the instance will always be created with a username matching ENV['USER']  If you send the parameter as 'username' it works as expected.
=> correct :user to :username in launch instance example

examples/image_create.rb
Link now needs a valid Google Storage URL.
Related context (API change): https://github.com/fog/fog-google/issues/22
Probably related issue: #40
=> Tiny comment ambiguity fix for image_create example

lib/fog/google.rb, lib/fog/google/requests/storage/copy_object.rb, lib/fog/google/requests/storage/put_object.rb
Currently, fog-google uses `CGI.escape` when sanitizing the names of files to be uploaded to Google Cloud. This causes `my file.txt` to become `my+file.txt` . I copied over the method used in `Rackspace.escape` to allow whitespace characters in filenames.
=> Allowing whitespace when uploading to google cloud

lib/fog/google/dns.rb
v1beta1 will deprecated eventually lets move to v1. This should be a no-op.
=> Update dns.rb to use v1 rather than v1beta1

test/integration/compute/test_regions.rb
Google added new DC and current test returns Failure:
TestRegions#test_all [/Users/mlazarov/projects/fog-google/test/integration/compute/test_regions.rb:11]:
Expected: 3
Actual: 4
This pull request will fix it.
=> Fix for regions test

lib/fog/google/models/dns/change.rb, lib/fog/google/models/dns/project.rb, lib/fog/google/models/dns/record.rb, lib/fog/google/models/dns/zone.rb, lib/fog/google/requests/dns/create_change.rb, lib/fog/google/requests/dns/create_managed_zone.rb, lib/fog/google/requests/dns/delete_managed_zone.rb, lib/fog/google/requests/dns/get_change.rb, lib/fog/google/requests/dns/get_managed_zone.rb, lib/fog/google/requests/dns/get_project.rb, lib/fog/google/requests/dns/list_changes.rb, lib/fog/google/requests/dns/list_managed_zones.rb, lib/fog/google/requests/dns/list_resource_record_sets.rb
Tiny doc fix. Noticed that DNS API reference links are now outdated.
Updated them to v1 and made sure they can be opened.
=> Updating dns comment links to v1

fog-google.gemspec, lib/fog/google/version.rb
Realized when testing https://github.com/fog/fog-google/issues/72.
=> Actually limit ruby version. Up version to 0.1.1

.editorconfig
Editor Config allows local per-project configuration to be expressed in a single
file, which makes it easy for one to work across many repos with many projects,
each of which may have its own preferred indentation, spacing, EOL, encoding,
etc. styles.
This change adds a 2-space indent for Ruby and YAML files; other rules can be
added quite easily. The file has a pointer to the project's homepage which
explains how to install editor-specific plugins to handle this config and how
to extend this config further.
=> Added .editorconfig for easier editing.

Rakefile, tasks/bundler.rake, tasks/console.rake, tasks/smoke.rake, tasks/test.rake
Before adding rubocop task, decided to refactor the rakefile into separate easily maintainable tasks.
What do you think about this?
/CC @icco @plribeiro3000
=> Refactoring the Rakefile into tasks

.gitignore, examples/storage.rb, lib/fog/google/requests/storage/delete_object.rb
#56 implemented a new escape method for create_object and copy_object, but didn't change the
delete_object method, leading to a situation when we can create a file with whitespace in it, but cannot actually delete it.
Additionally, added a new Google storage usage example.
=> Storage delete_object fix + new storage example

examples/l7_load_balance.rb, lib/fog/google/models/compute/target_http_proxy.rb, lib/fog/google/models/compute/target_instance.rb, lib/fog/google/models/compute/url_map.rb, lib/fog/google/models/storage/file.rb, tests/helper.rb
Fixes #34.
Also goes up and cleans up some rubocop warnings in `models/`
=> Consistent alias defintions

fog-google.gemspec
We still had Ruby 1.9 version fixup in the gemspec for rubocop and coveralls.
Considering the gemspec now doesn't allow <2.0, I presume we can remove it.
=> Removing <=1.9 rules from gemspec

README.md, examples/monitoring/metric_descriptors.rb, examples/monitoring/timeseries_collection.rb, examples/monitoring/timeseries_descriptors.rb, lib/fog/google/models/monitoring/metric_descriptor.rb, lib/fog/google/monitoring.rb, lib/fog/google/requests/monitoring/list_metric_descriptors.rb
Only real update was changing the API version to `v2beta2` and updating the name of the scope, otherwise, no real changes.
=> Update monitoring for v2beta2

lib/fog/google/requests/storage/get_object.rb, lib/fog/google/requests/storage/head_object.rb
The gem seems to support the http `Range:` header, however it doesn't accept the `206` response from google, which is required. (206 = Partial Content)
The following PR adds basic support for accepting `206 Partial Content`, allowing the `Range` header to be used to get objects from GCS.
=> Add support for partial content to support range header.

examples/get_list_images.rb, lib/fog/compute/google/models/images.rb
Currently, there are roughly 420 images across all GCE "official" image projects, but only about 20 that are not deprecated across the same set of projects.  I think most users will only want to see the "current" non-deprecated list.
=> Add list_images method to return current, non-deprecated images

lib/fog/storage/google_json/models/file.rb, test/integration/storage/test_files.rb
I'm not sure how someone missed this. When I was trying to setup CarrierWave and fog-google I ran into the arguments 1 for 0 error. After patching this method CarrierWave is working fine and also I ran the storage integration tests after making this change.
=> Fog::Storage::GoogleJSON::File#url method signature fix

lib/fog/google/models/storage/file.rb, lib/fog/google/version.rb
Add all predefined ACLs currently listed on the Google docs:
https://cloud.google.com/storage/docs/access-control.
Also changed the `public=` method to choose "project-private" in
the false case. (This is the default bucket ACL policy).
I'm not sure there is a best `public=false` choice, but from what I could tell it would involve some updates to `fog` and potentially `paperclip` to allow passing through the desired ACL. 
These addresses issue #71.
=> Update list of ACLs and change default private

README.md, examples/pubsub/subscriptions.rb, examples/pubsub/topics.rb, fog-google.gemspec, lib/fog/google.rb, lib/fog/google/models/pubsub/received_message.rb, lib/fog/google/models/pubsub/subscription.rb, lib/fog/google/models/pubsub/subscriptions.rb, lib/fog/google/models/pubsub/topic.rb, lib/fog/google/models/pubsub/topics.rb, lib/fog/google/pubsub.rb, lib/fog/google/pubsub/mock.rb, lib/fog/google/pubsub/real.rb, lib/fog/google/requests/pubsub/acknowledge_subscription.rb, lib/fog/google/requests/pubsub/create_subscription.rb, lib/fog/google/requests/pubsub/create_topic.rb, lib/fog/google/requests/pubsub/delete_subscription.rb, lib/fog/google/requests/pubsub/delete_topic.rb, lib/fog/google/requests/pubsub/get_subscription.rb, lib/fog/google/requests/pubsub/get_topic.rb, lib/fog/google/requests/pubsub/list_subscriptions.rb, lib/fog/google/requests/pubsub/list_topics.rb, lib/fog/google/requests/pubsub/publish_topic.rb, lib/fog/google/requests/pubsub/pull_subscription.rb, lib/fog/google/version.rb, tests/models/pubsub/received_message_tests.rb, tests/models/pubsub/subscription_tests.rb, tests/models/pubsub/subscriptions_tests.rb, tests/models/pubsub/topic_tests.rb, tests/models/pubsub/topics_tests.rb
This change adds some (not all) support for Google Pubsub (https://cloud.google.com/pubsub/overview)
The basics are there (topic creation/deletion/publishing, subscription creation/deleting/pulling, message acknowledging). I also added a very simple mock implementation as well as an example.
=> Add initial support for Google Pubsub

examples/storage.rb, lib/fog/storage/google_xml/real.rb, lib/fog/storage/google_xml/requests/get_object.rb, lib/fog/storage/google_xml/requests/get_object_acl.rb, lib/fog/storage/google_xml/requests/get_object_torrent.rb, lib/fog/storage/google_xml/requests/head_object.rb, lib/fog/storage/google_xml/requests/put_object_acl.rb
- Fixed more path escape issues on Storage XML, didn't update everything in https://github.com/fog/fog-google/pull/83
- Fixed regression in query enumeration in `signature` method.
- Added additional line to examples using the method that failed.
Fixing #124 
/CC @plribeiro3000 or @icco PTAL
=> Fix for XML storage issues

fog-google.gemspec
=> Lock activesupport dependency to <5 for backwards compatibility

lib/fog/storage/google_json/requests/put_bucket.rb
Fixes #142.
/cc @Temikus 
Note that I'm not entirely sure that this is the best way to solve this (and would welcome any discussion). Adding an additional optional parameter allows us to not break existing implementations, but it feels pretty free-form. I'm not sure it's beneficial to perform some sort of whitelist or something though as it will only restrict flexibility of the client in the future.
Thoughts?
=> Allow additional options to be applied to body

lib/fog/compute/google/requests/insert_server.rb
This value is incompatible with the default used by the GCE api;
specifically, the value 'MIGRATE' is incompatible with pre-emptible
instances. Fog-google should instead respect the default value GCE
chooses rather than imposing its own.
Fixes #136
=> Remove the default value of "MIGRATE" for "onHostMaintenance"

lib/fog/compute/google.rb, lib/fog/compute/google/models/images.rb, lib/fog/compute/google/requests/get_image_from_family.rb
Adding image family support. Fixes #131 
https://cloud.google.com/compute/docs/reference/latest/images/getFromFamily
This should allow dependent projects and utilities to avoid updating image references all the time where it's not needed.
/CC @icco @plribeiro3000 
Example:
```
[3] pry(main)> gce.images.get_from_family("centos-7")
=>   <Fog::Compute::Google::Image
name="centos-7-v20160718",
id="1351690450177672234",
kind="compute#image",
archive_size_bytes="2826321723",
creation_timestamp="2016-07-18T17:56:37.633-07:00",
deprecated=nil,
description="CentOS, CentOS, 7, x86_64 built on 2016-07-18",
disk_size_gb="10",
self_link="https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/centos-7-v20160718",
source_type="RAW",
status="READY",
project="centos-cloud", …
```
=> Adding image family support

fog-google.gemspec
Since 0.8.7 was released.
See https://github.com/google/google-api-ruby-client/issues/438
=> Removing activesupport workaround

lib/fog/storage/google_json/models/file.rb, lib/fog/storage/google_xml/models/file.rb
this creates parity with other providers such as AWS, allowing clients
to use S3 and Cloud Storage interchangeably
=> allow copy to accept an options parameter

lib/fog/storage/google_json/requests/put_object.rb, lib/fog/storage/google_json/requests/put_object_url.rb
Couple bugfixies
put_object_url - add expires param
put_object - fix meme-type autodetect data.is_a?(File) returns false for file object
=> Fix put_object_url and mime-type autodetect

lib/fog/google/requests/pubsub/create_subscription.rb
Existing code assigns the push_endpoint value directly to pushConfig,
which is not matching the structure defined at
https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions#PushConfig
Instead we just directly take the supplied hash.
=> Fix push_config to be proper structure

lib/fog/storage/google_json.rb, lib/fog/storage/google_json/models/file.rb, lib/fog/storage/google_json/models/files.rb, lib/fog/storage/google_json/requests/list_objects.rb
Closes #151 
Guys, I'm not sure that the json storage implementation is working; I couldn't find an implementation of `list_objects` and had to add one, and the file/directory abstractions contain a lot of stuff that doesn't match to the json api (hence the addition of the `name` alias change below in `file.rb`).
I'm trying to make this change as minor as possible in order to fix the bug, but I think it might be beneficial to revisit the entire storage json implementation.
=> Fix bug where listing of bucket causes infinite loop

test/integration/pubsub/test_pubsub.rb
These use the minitest format rather than the shinto test-style. I tackled pubsub as I'm the most familiar with it, and I wanted to get early-feedback in case I'm writing minitests in a bad style.
=> Add minitest pubsub tests, which test all the request methods

lib/fog/storage/google_json/models/directories.rb, lib/fog/storage/google_json/models/directory.rb, lib/fog/storage/google_json/models/file.rb, lib/fog/storage/google_json/models/files.rb, lib/fog/storage/google_xml/models/file.rb
In lib/fog/google/shared.rb:181 a Fog::Error::NotFound is raised
when a request returns 404 but in our models we were rescuing
Excon::Error::NotFound.
Fixing #161 
@plribeiro3000 @icco PTAL
Seems to work correctly now:
```
λ bundle exec rake console
[1] pry(main)> connection = Fog::Storage::GoogleJSON.new; :ok
=> :ok
[2] pry(main)> dir = connection.directories.get('fog-testing')
=>   <Fog::Storage::GoogleJSON::Directory
key="fog-testing"
>
[3] pry(main)> dir.files.get("idonotexist.jpeg")
=> nil
[4] pry(main)> dir.files.head("idonotexist.jpeg")
=> nil
[9] pry(main)> dir.files.get("00818_sanfranciscoseascape_2560x1600.jpeg");
[10] pry(main)> file = dir.files.get("00818_sanfranciscoseascape_2560x1600.jpeg");
...
deleted the file
...
[11] pry(main)> file.destroy
=> false
[12] pry(main)> …
```
=> Fixing NotFound error class in Storage JSON

lib/fog/compute/google/models/server.rb
Fixes #166
Now disk autodelete can be called with one argument if there's only
one disk attached:
```
[3] pry(main)> server = gce.servers.get("server-id-cdc128b11b50");
[4] pry(main)> server.set_disk_auto_delete(true)
=>   <Fog::Compute::Google::Operation
...
status="DONE",
...
```
I think this is a good compromise, since the canonical API call target is "deviceName", but I don't want to introduce iterative logic that enumerates all disks and scans their source URL's.
@icco PTAL
=> Improve disk autodelete method

lib/fog/google/shared.rb
As mentioned in issue #153 the Google Api client supports proxies.
This is an inital work in progress at getting proxy support in fog-google.
This is my first look at the fog-google gem, so I'm not that familiar.
I know this PR isn't complete, but thought I'd make an initial attempt and ask for feedback on what exactly else needs doing to get proxy support into fog-google.
Thanks :)
=> [WIP] Adding Proxy support

lib/fog/compute/google/requests/insert_server.rb
First attempt at writing some yard doc. It's on a request-level method, but I figured given the large amount of customization available for creating servers it might be useful to someone. Next attempt will be on the general collection methods.
=> Add documentation (and example) for request level insert_server

examples/create_instance.rb, examples/get_list_images.rb, examples/metadata.rb, examples/network.rb, lib/fog/compute/google/mock.rb, lib/fog/compute/google/models/image.rb, lib/fog/compute/google/models/server.rb, lib/fog/compute/google/models/servers.rb, tests/helper.rb, tests/requests/compute/disk_tests.rb
Follow-up to #185 
It seems that add_ssh_key never actually performed an operation but rather changed the metadata of the currently saved `server` object. Since one can ?no longer? call `server.save` on an existing instance, this method seems useless without an actual call to metadata update.
@icco @selmanj - PTAL, since I think I may be missing something.
P.S. Updated all the instance templates, since some older wheezy images do not support `ssh-key` metadata + we had some images from !2014! in tests/bootstrap.
=> Make server.add_ssh_key an operation

test/helpers/client_helper.rb, test/integration/compute/requests/test_compute_address_requests.rb, test/integration/compute/test_addresses.rb, test/integration/compute/test_compute_addresses_collection.rb
This adds some basic end-to-end tests covering requests for the 'addresses' resource in compute. It's very similar to the pubsub tests.
I was going to use this as well as the pubsub tests to try to generalize some test helpers for testing basic CRUD testing without having to add all the boilerplate, but I'm holding off on that for now as my first attempt made the tests too hard to read. I'm opening a PR for this at the moment though as it's useful in its current form.
=> Add tests for addresses resource

lib/fog/google/shared.rb
=> Check for nil in google_client_options and use a {} if not set

examples/create_instance.rb, lib/fog/compute/google/models/server.rb
Fixing #189 by separating the logic into a private method.
@selmanj PTAL
P.S. Fixed our example since `:user` attribute doesn't actually exist in the core Server model:
```
attr_writer :username, :private_key, :private_key_path, :public_key, :public_key_path, :ssh_port, :ssh_options
```
=> Fixing regression in Server.insert

lib/fog/google/version.rb
Quick releasing 0.5.2 due to regression in #190 still present in 0.5.1
=> Releasing 0.5.2

lib/fog/compute/google.rb, lib/fog/dns/google.rb, lib/fog/google/monitoring.rb, lib/fog/google/pubsub.rb, lib/fog/google/sql.rb, lib/fog/storage/google_json.rb
Cleaned up the recognizes option a bit and added :google_client_options to suppress warning.
Fixes #197
=> Add recognize for google client options

.travis.yml
We now build on Trusty instead of Precise.
Limiting to just one version of 2.3, and major versions of 2.4.
=> Tweak what versions we build and what OS

lib/fog/google/requests/pubsub/create_subscription.rb
I'm getting 
```
[NoMethodError]: undefined method `empty?' for nil:NilClass
/opt/rh/cfme-gemset/gems/fog-google-0.5.2/lib/fog/google/requests/pubsub/create_subscription.rb:29:in `create_subscription'
/opt/rh/cfme-gemset/gems/fog-google-0.5.2/lib/fog/google/models/pubsub/subscription.rb:71:in `save'
/opt/rh/cfme-gemset/gems/fog-core-1.43.0/lib/fog/core/collection.rb:51:in `create'
```
The calling code is 
```ruby
google.subscriptions.create(:name  => subscription_name, :topic => topic_name)
```
My guess is either https://github.com/fog/fog-google/pull/168 introduced this regression because [this line](https://github.com/fog/fog-google/blob/4ac58a77f91f4d6877d77133b6bcee33403951d8/lib/fog/google/models/pubsub/subscription.rb#L71) passes `push_config` and if it's `nil` it will pass `nil`. …
=> check if push_config is present before checking for entries

.fog.example, README.md
[trying my first pull request here! So apologies for newbbisities]
Adding a sample file for .fog and proposing in the docs to just append this sample into your home fog (I'm not an expert but I presume this is safer than a CP as people might have stuff already in there). Ideally if you like this idea I can actually remove the same stuff from README (more DRY) - but I wasnt sure.
=> Adding .fog.example and amending docs

lib/fog/storage/google_json/models/files.rb
```ruby
#! /usr/bin/env ruby
#
require "bundler"
Bundler.require(:default, :development)
connection = Fog::Storage::Google.new({
google_project: 'icco-fog-test',
google_client_email: 'test-account@icco-fog-test.iam.gserviceaccount.com',
google_json_key_location: './key.json'})
dir = connection.directories.get('pivotal-ally-6679')
p dir.files.all()
```
If you go and create a new empty bucket and run the above snippet, your code will throw 
```
/Users/natwelch/.rvm/gems/ruby-2.4.0/gems/fog-core-1.44.3/lib/fog/core/collection.rb:76:in `load': undefined method `each' for nil:NilClass (NoMethodError)
from /Users/natwelch/.rvm/gems/ruby-2.4.0/gems/fog-google-0.5.3/lib/fog/storage/google_json/models/files.rb:20:in `all'
from ./test-storage.rb:18:in `<main>'
```
Updated, it now returns 
``` …
```
=> Don't fail if no items

lib/fog/google/pubsub/real.rb, lib/fog/google/requests/pubsub/acknowledge_subscription.rb, lib/fog/google/requests/pubsub/create_subscription.rb, lib/fog/google/requests/pubsub/create_topic.rb, lib/fog/google/requests/pubsub/delete_subscription.rb, lib/fog/google/requests/pubsub/delete_topic.rb, lib/fog/google/requests/pubsub/get_subscription.rb, lib/fog/google/requests/pubsub/get_topic.rb, lib/fog/google/requests/pubsub/list_subscriptions.rb, lib/fog/google/requests/pubsub/list_topics.rb, lib/fog/google/requests/pubsub/publish_topic.rb, lib/fog/google/requests/pubsub/pull_subscription.rb, test/integration/pubsub/test_pubsub_requests.rb
This breaks compatibility with the previous excon based approach
as keeping it would require us to manually wrap every API
client operation in an excon response.
Additionally, all mocks have been deleted and left unimplemented.
However, the tests have been migrated and currently pass.
Looking for review to make sure this style is fine to continue with for the pubsub models. Thanks!
=> Upgrade PubSub requests to >= 0.11

lib/fog/google/models/pubsub/subscription.rb, lib/fog/google/models/pubsub/subscriptions.rb, lib/fog/google/models/pubsub/topic.rb, lib/fog/google/models/pubsub/topics.rb, test/integration/pubsub/pubsub_shared.rb, test/integration/pubsub/test_pubsub_models.rb, test/integration/pubsub/test_pubsub_requests.rb
Models have been minimally changed to work against the rewritten
requests. Additionally, model tests have been included.
This follows up from the previous upgrade of the PubSub requests.
df470108cd944ec09d81cf56c6c556f339ba7dc8
=> Upgrade PubSub models to >= 0.11

.rubocop.yml
This is the lowest version of ruby travis is run against, so hound
should match to prevent version mismatches.
This will prevent hound from requesting changes which are
incompatible with versions we support. An example of such a
feature is safe navigation, not available before 2.3. ie,
github.com/fog/fog-google/pull/231#pullrequestreview-49858308
=> Explicitly set rubocop TargetRubyVersion to 2.1

ci/.gitignore, ci/README.md, ci/credentials.yml.tpl, ci/docker-image/Dockerfile, ci/pipeline.yml, ci/tasks/run-int.sh, ci/tasks/run-int.yml, ci/tasks/utils.sh
This pipeline performs two functions.
First, it performs an integration test of the
upgrade-google-client branch whenever new changes appear there.
Second, it runs integration tests against every PR with the
`integrate` label. This allows whitelisted PRs to be tested
automatically before being merged. Status is updated on the
PR when the test completes.
When #210 lands, switch the pipeline to work against master.
=> Introduce Concourse pipeline

lib/fog/compute/google.rb, lib/fog/dns/google.rb, lib/fog/google/monitoring.rb, lib/fog/google/pubsub.rb, lib/fog/google/shared.rb, lib/fog/google/sql.rb, lib/fog/storage/google_json.rb
Missed this in https://github.com/fog/fog-google/pull/211, gets rid of `[fog][WARNING] Unrecognized arguments: google_auth` warnings.
=> Add google_auth to the list of recognized options

lib/fog/compute/google.rb, lib/fog/compute/google/models/global_address.rb, lib/fog/compute/google/models/global_addresses.rb, lib/fog/compute/google/models/ssl_certificate.rb, lib/fog/compute/google/models/ssl_certificates.rb, lib/fog/compute/google/models/target_http_proxy.rb, lib/fog/compute/google/models/target_https_proxies.rb, lib/fog/compute/google/models/target_https_proxy.rb, lib/fog/compute/google/requests/delete_global_address.rb, lib/fog/compute/google/requests/delete_ssl_certificate.rb, lib/fog/compute/google/requests/delete_target_https_proxy.rb, lib/fog/compute/google/requests/get_global_address.rb, lib/fog/compute/google/requests/get_ssl_certificate.rb, lib/fog/compute/google/requests/get_target_https_proxy.rb, lib/fog/compute/google/requests/insert_global_address.rb, lib/fog/compute/google/requests/insert_ssl_certificate.rb, lib/fog/compute/google/requests/insert_target_https_proxy.rb, lib/fog/compute/google/requests/list_ssl_certificates.rb, lib/fog/compute/google/requests/list_target_https_proxies.rb, lib/fog/compute/google/requests/set_target_https_proxy_url_map.rb
Those features are needed if you want to deploy an HTTP(S) load balancer with Fog and want to use SSL termination.
=> support for SSL certificates, https proxies and global IP addresses

README.md
This reverts commit 8957f5bd206dd95ef1eedbb5543a1f1e99bd4868.
This is an (admittedly) embarassing mistake of mine when showing git
workflow to a colleague. Apologies for the hassle and let me know
if you'd like to rebase. 
However, I felt uneasy doing a rebase and
force push on a large public repo.
@icco
=> Revert "Test commit please ignore"

lib/fog/compute/google/models/instance_group.rb, lib/fog/compute/google/models/instance_groups.rb, lib/fog/compute/google/models/servers.rb, lib/fog/compute/google/requests/add_instance_group_instances.rb, lib/fog/compute/google/requests/delete_instance_group.rb, lib/fog/compute/google/requests/get_instance_group.rb, lib/fog/compute/google/requests/get_server.rb, lib/fog/compute/google/requests/insert_instance_group.rb, lib/fog/compute/google/requests/list_aggregated_instance_groups.rb, lib/fog/compute/google/requests/list_instance_group_instances.rb, lib/fog/compute/google/requests/list_instance_groups.rb, lib/fog/compute/google/requests/remove_instance_group_instances.rb
A few questions/things I'm not sure of:
1) I haven't reimplemented the deprecated methods here https://github.com/fog/fog-google/blob/master/lib/fog/compute/google/models/instance_groups.rb#L35-L51 - should I? FWIW I'm not sure they even work, e.g. `unless params[:instance] == Array` is missing one `=` to make sense :)
2) `InstanceGroup#save` throws `alreadyExists` error - is that normal? I can change the name and attempt to save it, but then it fails on `subnetwork` as that's apparently ready-only.
=> Upgrade google client instance groups

lib/fog/compute/google/models/server.rb
as method is not resolved, no server has external IP returned. 
Probably intended method was:  http://ruby-doc.org/core-2.0.0/Enumerable.html#method-i-flat_map
as workaround, until this is merged and released users can use alias_method:
```
module Enumerable
alias_method :flatMap, :flat_map
end
```
=> method :flatMap not resolved

lib/fog/storage/google_json/requests/put_object.rb, test/integration/storage/test_objects.rb
[Paperclip](https://github.com/thoughtbot/paperclip) passes `:content_type` to fog which caused fog-google not to use the data’s path (and therefore causing a `Google::Apis::ClientError`). See #289 for more information.
=> Fix file uploading when using Paperclip

lib/fog/compute/google/models/disk.rb
At some point we deleted this function: https://github.com/fog/fog-google/blame/v0.5.0/lib/fog/compute/google/models/disk.rb#L59-L70, which caused https://github.com/fog/fog-google/issues/300. This is a fix, altho I'm not entirely sure if we should even have `get_as_boot_disk` anymore.
=> Remove call to nonexistent function

lib/fog/compute/google/models/server.rb
Setting service accounts should use an array of hashes instead
of a hash. See the resource.serviceAccounts[] field in the below
Google API document for details.
https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert
=> Fix setting service accounts and scopes on GCE instances

lib/fog/storage/google_json.rb, lib/fog/storage/google_json/requests/delete_object_url.rb, lib/fog/storage/google_xml.rb, lib/fog/storage/google_xml/requests/delete_object_url.rb
This PR exposes pre-signed URLs for Google Cloud Storage
=> Expose Storage pre-signed object delete url

lib/fog/compute/google/models/disk.rb
The correct name is :auto_delete and not :autoDelete.
=> Fix compute disk auto delete hash key

lib/fog/storage/google_json/requests/get_object_url.rb, lib/fog/storage/google_xml/requests/get_object_url.rb
`get_object_url` invokes itself as logging message causing an `ArgumentError`
=> Fix deprecation messages raising ArgumentError

lib/fog/storage/google_json/models/file.rb
1.paperclip will pass “fog_public” to fog, this mean the file will be public.
2. FILE_INSERTABLE_FIELDS is not support “acl”, so removed it.
=> add fog_public support in JSON API

.travis.yml, examples/create_instance.rb, examples/get_list_images.rb, examples/load-balance.rb, examples/metadata.rb, examples/network.rb, fog-google.gemspec, lib/fog/compute/google/models/disk.rb, lib/fog/compute/google/requests/insert_disk.rb
Fixing the disk part of #315, recreating the PR without my changes to rubocop to make sure I'm not causing HoundCI to act up.
Mainly:
Added logic to get the image from name if the format is not
compatible with new Google API Client and added a
user-friendly error if image is specified incorrectly
Disk autogenerated object already accepts :source_image as an
option so removing it from request parameters
Zone is already set in parameters so should not be duped in
options
=> Fix instance workflow - take 2

lib/fog/compute/google/models/subnetworks.rb
The fog was unable to list subnetworks using the `connection.subnetworks.all` call.
In recent versions of `google-api-client`, the hash response keys had been changed from strings to symbols. This is one of uncaught appearances. :wink:
=> Listing all subnetworks symbol key

.rubocop.yml, fog-google.gemspec, lib/fog/compute/google.rb, lib/fog/compute/google/models/network.rb, lib/fog/compute/google/models/server.rb, lib/fog/compute/google/requests/insert_disk.rb, lib/fog/compute/google/requests/insert_url_map.rb, test/integration/compute/addresses/addresses_shared.rb, test/integration/compute/test_compute_addresses_collection.rb, test/integration/compute/test_compute_networks_collection.rb, test/integration/factories/collection_factory.rb, test/integration/monitoring/test_timeseries.rb, test/integration/storage/test_files.rb, test/integration/test_authentication.rb
Fixing up tests so we can rely on CI for breakages. Starting with a rather embarrassing regression I introduced.
=> Fixing tests

lib/fog/storage/google_xml/models/directory.rb, lib/fog/storage/google_xml/models/file.rb, lib/fog/storage/google_xml/requests/put_bucket.rb, lib/fog/storage/google_xml/requests/put_object.rb, lib/fog/storage/google_xml/requests/put_object_acl.rb, lib/fog/storage/google_xml/utils.rb
As per issue #324, I decided to make a start on this functionality and would like to know what folks think. I'm not sure which tests need writing and where, especially since things are migrating to minitest. Some guidance would be appreciated.
Also, the changes introduced here are pretty much entirely copied from https://github.com/fog/fog-aws/blob/master/lib/fog/aws/requests/storage/put_object_acl.rb#L39.
=> Add support for using predefined ACLs, fixes #324

.gitignore, README.md, examples/create_instance.rb, lib/fog/compute/google/models/server.rb, lib/fog/compute/google/requests/insert_server.rb, lib/fog/compute/google/requests/set_server_metadata.rb, test/integration/compute/test_servers.rb
- Added a quick helper to process tags the old-fashioned way,
as {:items => []} is harder to write
- Added :zone_name alias in instances to match Disk model
- Fixed create_instance example
Fixes #315
=> WIP - Fixing instance creation workflow

tasks/test.rake
Now one can just `$ rake test:compute` and run only the compute subsection of tests.
Planning to try and parallelise our CI.
=> Breakout test tasks for parallelization

ci/pipeline.yml, ci/tasks/run-int.sh, ci/tasks/run-int.yml, tasks/test.rake
- Parallelising our CI, pipeline will now be running jobs in parallel and look something like this:
, allowing to get the results for relevant sections ASAP and compartmentalising test so they can be rerun if needed (in case of underlying API flakiness or collisions).
- Added separate test tasks for each section of fog for quicker testing:
```
rake test               # Run all integration tests
rake test:parallel      # Run all integration tests in parallel
rake test:compute       # Run Compute API tests
rake test:monitoring    # Run Monitoring API tests
rake test:pubsub        # Run PubSub API tests
rake test:sql           # Run SQL API tests
rake test:storage       # Run Storage API tests
```
- Added a `rake test:parallel` task, which has about 3X performance with a caveat of ugly (but …
=> WIP - Parallelize CI, update run-int task

lib/fog/compute/google/models/target_pool.rb
Without that, the Hash[results] does not work as expected.
Another option is to not return the same signature when an instance name is specified (data can be returned directly)
=> Fix get_health when called with an instance name

lib/fog/storage/google_json/requests/put_object.rb, test/integration/storage/test_objects.rb
We had some unclear situation while were testing file uploads. When we sent `nil` we got `ClientError` stating that URL is bad and should be starting from `/upload`. All of that were caused by invalid/unexpected command being created https://github.com/google/google-api-ruby-client/blob/e3b8c800d649da00748d4605d847b342480ecc73/generated/google/apis/storage_v1/service.rb#L1795
=> Added test on put_object with `nil` as object body

tasks/test.rake, test/unit/compute/test_collections.rb, test/unit/compute/test_common_collections.rb, test/unit/compute/test_common_models.rb
This should help us keep models/collections the same across the board and avoid issues like #352 and help newcomers iterate quickly to avoid us needing to point out missing methods like in #348
=> Adding unit tests

fog-google.gemspec, lib/fog/compute/google/mock.rb, lib/fog/google/shared.rb
=> Bumping Google API client to 0.23

lib/fog/compute/google.rb, lib/fog/compute/google/models/instance_group_manager.rb, lib/fog/compute/google/models/instance_group_managers.rb, lib/fog/compute/google/models/instance_template.rb, lib/fog/compute/google/models/instance_templates.rb, lib/fog/compute/google/requests/abandon_instances.rb, lib/fog/compute/google/requests/delete_instance_group_manager.rb, lib/fog/compute/google/requests/delete_instance_template.rb, lib/fog/compute/google/requests/get_instance_group_manager.rb, lib/fog/compute/google/requests/get_instance_template.rb, lib/fog/compute/google/requests/insert_instance_group_manager.rb, lib/fog/compute/google/requests/insert_instance_template.rb, lib/fog/compute/google/requests/list_aggregated_instance_group_managers.rb, lib/fog/compute/google/requests/list_instance_group_managers.rb, lib/fog/compute/google/requests/list_instance_templates.rb, lib/fog/compute/google/requests/recreate_instances.rb, lib/fog/compute/google/requests/set_instance_template.rb
Sorry, did not write tests, but I'm using it in prod.
=> Add templates and instance group managers

lib/fog/compute/google/models/images.rb
Google recently removed `google-containers` from the [Public images list](https://cloud.google.com/compute/docs/images).
Any call to `.images.all` results in an exception:
```
> compute = ::Fog::Compute.new(...)
> compute.images.all
...
Sending HTTP get https://www.googleapis.com/compute/v1/projects/google-containers/global/images?
403
...
Google::Apis::ClientError: accessNotConfigured: Access Not Configured. Compute Engine API has not been used in project 255964991331 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=255964991331 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
from …
```
=> Fix remove google-containers images listing

lib/fog/storage/google_xml/utils.rb, test/unit/storage/test_xml_requests.rb
This should fix ‘+’ being inserted instead of %20 when using spaces in filename.
Fixes #357
=> Switch to Fog::Google.escape to fix whitespace

CHANGELOG.md, lib/fog/compute/google/models/server.rb, lib/fog/compute/google/models/servers.rb, test/unit/compute/test_server.rb, test/unit/storage/test_xml_requests.rb
For some reason those were abandoned in 1.0, so core examples and `bootstrap` no longer worked.
E.g. the following no longer provisioned the keys properly:
```
server = connection.servers.create(
:name => "fog-smoke-test-#{Time.now.to_i}",
:disks => [disk],
:machine_type => "n1-standard-1",
:private_key_path => File.expand_path("~/.ssh/id_rsa"),
:public_key_path => File.expand_path("~/.ssh/id_rsa.pub"),
:zone => "us-central1-f",
:username => ENV["USER"],
:tags => ["fog"],
:service_accounts => { :scopes => %w(sql-admin bigquery https://www.googleapis.com/auth/compute) }
)
```
This patch will make sure `:private_key_path` and `:public_key_path` are processed properly again.
Fixing #362 
Not even mentioning that `save()` shouldn't have had arguments in the first place.
But that's going to be …
=> Fixing Fog::Server user/sshkey workflow

CHANGELOG.md, examples/bootstrap.rb, lib/fog/compute/google/models/servers.rb, test/integration/compute/test_servers.rb
- Add tests for `Fog::Compute::Google::Server.bootstrap`
- Set disks to autodelete for servers created with `Fog::Compute::Google::Server.bootstrap`
+ some drive-by fixes to `.bootstrap`
Fixes #17
=> Bootstrap autodelete

CHANGELOG.md, Gemfile, README.md, ci/credentials.yml.template, ci/pipeline.yml, ci/tasks/run-int.sh, fog-google.gemspec, tasks/test.rake, test/helpers/test_helper.rb, test/integration/compute/test_coverage.rb, test/integration/monitoring/test_coverage.rb, test/integration/pubsub/test_coverage.rb, test/integration/sql/test_coverage.rb, test/integration/storage/test_coverage.rb
Alright, let's get this ball rolling. 
Plan:
Fixes #88
=> Restore coverage checks

lib/fog/compute/google/models/firewall.rb, test/integration/compute/test_firewalls.rb, test/integration/compute/test_instance_groups.rb, test/integration/compute/test_machine_types.rb, test/integration/factories/firewalls_factory.rb, test/integration/factories/instance_groups_factory.rb
Further improving coverage:
- Instance groups
- Machine types
- Firewalls
+ a drive by fixes:
- Firewall sanity check
=> Add more test coverage

lib/fog/storage/google_json.rb, lib/fog/storage/google_json/real.rb
Currently, fog-google doesn't allow users to set timeout options when they upload objects to GCS.
This PR extends the support.
Here, in GitLab's usage, we can pass those params as the followings.
```
connection:
provider: Google
google_project: xxx
google_client_email: xxx
google_json_key_location: xxx
open_timeout_sec: 111
read_timeout_sec: 123
send_timeout_sec: 321
```
=> Add timeout options (Google::Apis::ClientOptions) to GoogleJSON API

examples/create_instance.rb, examples/get_list_images.rb, examples/load-balance.rb, examples/metadata.rb, examples/network.rb, lib/fog/compute/google/models/server.rb, lib/fog/compute/google/models/servers.rb, lib/fog/compute/google/requests/insert_server.rb, test/integration/compute/test_addresses.rb
Debian 8 has reached its end-of-life as of 18th June 2018 at which point it is in the Long-Term Support stage of the Debian lifecycle (which is best effort). 
Debian 9 “Stretch” is the current stable release of Debian.
=> Deprecate Debian 8 references

CHANGELOG.md, fog-google.gemspec, lib/fog/compute/google/models/backend_service.rb, lib/fog/compute/google/models/disk.rb, lib/fog/compute/google/models/firewall.rb, lib/fog/compute/google/models/forwarding_rule.rb, lib/fog/compute/google/models/global_address.rb, lib/fog/compute/google/models/global_forwarding_rule.rb, lib/fog/compute/google/models/http_health_check.rb, lib/fog/compute/google/models/image.rb, lib/fog/compute/google/models/instance_group_manager.rb, lib/fog/compute/google/models/instance_template.rb, lib/fog/compute/google/models/route.rb, lib/fog/compute/google/models/server.rb, lib/fog/compute/google/models/subnetwork.rb, lib/fog/compute/google/models/target_http_proxy.rb, lib/fog/compute/google/models/target_instance.rb, lib/fog/compute/google/models/target_pool.rb, lib/fog/compute/google/models/url_map.rb, lib/fog/dns/google/models/record.rb, lib/fog/google/models/sql/instance.rb, lib/fog/google/models/sql/user.rb, test/helpers/integration_test_helper.rb, test/helpers/test_helper.rb, test/integration/compute/test_servers.rb, test/integration/factories/collection_factory.rb, test/integration/factories/disks_factory.rb
Server is our most complicated model but it has the worst test coverage.
This is trying to improve it and fix the docs while I'm at it.
Due to the need to instantiate a bunch of servers during the test this slows them down quite a bit...
Looking at ballpark figures - 73 minutes :|
I'll start thinking about speeding things up. I think we can parallelise things more, but that requires careful planning of cleanup (since different API's can trump eachother).
=> Improve Compute coverage

CHANGELOG.md, fog-google.gemspec
This should alleviate #417 until we can properly upgrade all the tests, etc.
Additionally, locks the major versions of other upstream deps.
=> Fix core dep

lib/fog/compute/google/real.rb, lib/fog/dns/google/real.rb, lib/fog/google/monitoring/real.rb, lib/fog/google/pubsub/real.rb, lib/fog/google/shared.rb, lib/fog/google/sql/real.rb, lib/fog/storage/google_json/real.rb
That feature was broken with Google's gem update and
this PR: https://github.com/fog/fog-google/commit/5ec9a15e1a0645e5ce9673c71468975db4926efb#diff-c6b2ed334d1938d66b4e168f255abbb7L140
Now it's back.
=> apply given API service client options

CHANGELOG.md, fog-google.gemspec, lib/fog/google/version.rb
This is a tiny patch release to relax fog-core constraint and keep compatibility with ManageIQ.
Ref: https://github.com/ManageIQ/manageiq-providers-google/pull/73
=> Release 1.8.1 🛠

lib/fog/storage/google_json/requests/get_object.rb
Allows the the gem to clean up temporary files at execution time rather than relying on the Garbage Collector to clean up or other parts of the MRI calling the object space finalize methods.
=> Allow the api to close Tempfiles inline

.travis.yml, CHANGELOG.md, Gemfile, examples/create_instance_with_attached_disk.rb, fog-google.gemspec, lib/fog/compute/google/models/disk.rb, lib/fog/compute/google/models/disks.rb, lib/fog/compute/google/models/snapshot.rb, test/integration/compute/core_compute/test_disks.rb
Will close #425 in favor of this for JRuby fixes.
Otherwise - mainly docs + tests for attached disks behaviour, to avoid confusion like in #434.
=> JRuby fixes + disk tests/docs

ci/README.md, ci/tasks/run-int.yml
- Concourse now requires all task parameters to be explicitly called out.
- Updated readme a bit, removing obsolete Concourse setup instructions. 
(TF modules for our current setup will be published here soon)
=> Update to Concourse v4.0

lib/fog/google/shared.rb
Previously, `fog-google` implicitly required a service account to
authenticate against the Google Cloud Platform APIs.
This change allows the use of Application Default Credentials so that
end users can authenticate without a service account for development,
testing, and one-off interactions.
This change does not check any of the different environment variables
that Google documents for its client libraries and instead reads a
well-known file path for ADCs.
=> feat: Allow Google Application Default Credentials

.fog.example, CONTRIBUTING.md, ci/credentials.yml.template, ci/pipeline.yml, ci/tasks/run-int.sh, ci/tasks/run-int.yml, lib/fog/compute/google.rb, lib/fog/dns/google.rb, lib/fog/google/monitoring.rb, lib/fog/google/pubsub.rb, lib/fog/google/shared.rb, lib/fog/google/sql.rb, lib/fog/storage/google_json.rb, test/integration/test_authentication.rb, test/unit/storage/test_json_requests.rb
This PR centers around:
- Reworking credentials workflow to be easier to read and fall back to google application default credentials
- Removing deprecated `google_client_email` parameter everywhere
=> WIP Better credential workflow

lib/fog/dns/google.rb, lib/fog/google/monitoring.rb, lib/fog/google/pubsub.rb, lib/fog/google/sql.rb, lib/fog/storage/google_json.rb
Add :google_application_default to avoid “unrecognised parameter” warnings
=> Update service options with new client option

lib/fog/compute/google/models/address.rb, test/integration/compute/core_networking/test_addresses.rb, test/integration/monitoring/test_metric_descriptors.rb
- Tempfix for the failing SD tests due to #451 
- Some fixes to `Addresses` tests
- `Addresses.server = ` method will now execute a synchronous operation
=> WIP Minor test fixes and additions

ci/pipeline-dev.yml, ci/tasks/run-int.sh, ci/tasks/run-int.yml
Implementing worker-side caching of dependencies between jobs. This should shave off 1-2 minutes for each build task and lower the amount of ingress traffic to workers.
=> Cache bundling artefacts

lib/fog/google/models/sql/user.rb, test/integration/factories/sql_v1_users_factory.rb
Semi-temporary fix for #462
Tests are still very much valid but depending on the outcome of the internal issue we may need to make some adjustments.
=> Add “host” parameter to SQL user factory

lib/fog/compute/google/models/server.rb
=> Fixes metadata format for 'ssh-keys' key

test/integration/compute/core_compute/test_servers.rb
Added test as discussed on [PR-455](https://github.com/fog/fog-google/pull/455#issuecomment-499747221)
=> Test to verify ssh-key value contains comment using an username

fog-google.gemspec, test/integration/compute/core_compute/test_zones.rb, test/integration/monitoring/test_timeseries.rb
This takes #468 and tries to fix the failing tests as well.
=> Upgrade google-api-client, fix broken tests

test/integration/monitoring/test_metric_descriptors.rb
Fixes #451 
```
λ bundle exec rake test TESTOPTS=" --name=/test_metric_descriptors_all_page_size/"                                                                            (130)
Started with run options --name=/test_metric_descriptors_all_page_size/ --seed 6843
TestMetricDescriptors
test_metric_descriptors_all_page_size                           PASS (2.19s)
Finished in 2.20231s
1 tests, 2 assertions, 0 failures, 0 errors, 0 skips
```
=> Removing SD test skip

ci/tasks/run-int.sh, fog-google.gemspec, lib/fog/google/requests/monitoring/create_timeseries.rb
It seems that the GoogleAPI client has made a breaking change again.
The method `create_time_series` no longer exists in the library and looks to have been replaced with `create_project_timeseries`.
We also need to bump the minimum gem version as this was introduced somewhere around `0.31`
=> Fix Monitoring#create_time_series

test/integration/compute/core_compute/test_servers.rb
Fixing test flakiness.
It looks like adding ssh keys has become slower since we didn't notice this before.
=> Make the ssh key operation synchronous in tests

fog-google.gemspec
Reverts fog/fog-google#481 due to causing a regression around  https://github.com/fog/fog-google/pull/422
We need to push out a minor release before we can update that.
=> Revert "Update fog-core requirement from <= 2.1.0 to <= 2.3.0"

lib/fog/compute/google.rb, lib/fog/compute/google/models/server.rb, lib/fog/compute/google/requests/set_server_machine_type.rb, test/integration/compute/core_compute/test_servers.rb
Adds a set_server_machine_type request. This is useful for changing a server's machine type although the instance must be stopped to do so.
Signed-off-by: gscho <greg.c.schofield@gmail.com>
=> Created set machine type request

lib/fog/compute/google.rb, lib/fog/compute/google/models/server.rb, lib/fog/compute/google/requests/reset_windows_password.rb, test/integration/compute/core_compute/test_servers.rb
These are a few small changes to add the ability to reset windows passwords as described in fog/fog-google#494.
The majority of the code was modified from the Python-based Google provided example: https://github.com/GoogleCloudPlatform/compute-image-windows/blob/master/examples/windows_auth_python_sample.py
I have implemented everything as a Request, though I am not sure if this would be better added to the Server model.  My thoughts in favor of the Server model are that the request does not match extremely closely to an API, rather is uses the API to set the Metadata values on an instance.  However, the downside to adding it to the Server model is that not all Windows images would have this functionality so it might be more complicated to adjust the Server model.
Resolves #494
=> Add support to reset Windows passwords

lib/fog/compute/google.rb, lib/fog/compute/google/models/server.rb, lib/fog/google/requests/pubsub/pull_subscription.rb, test/helpers/integration_test_helper.rb, test/integration/pubsub/test_pubsub_models.rb, test/integration/pubsub/test_pubsub_requests.rb
It used to be relevant("RUNNING_STATE"), but no longer is.
See: fog/fog@7814ae5
Fixes #391
=> Remove unneeded constants

test/helpers/integration_test_helper.rb, test/integration/monitoring/test_timeseries.rb
Drive-by fix for an old TODO in monitoring tests.
=> DRY up the retry methods in monitoring tests

.rubocop.yml, fog-google.gemspec, lib/fog/google/shared.rb, lib/fog/storage/google_json.rb, lib/fog/storage/google_json/mock.rb, lib/fog/storage/google_json/real.rb, lib/fog/storage/google_json/utils.rb, lib/fog/storage/google_xml/requests/get_bucket.rb, tasks/changelog.rake
This option is added to enable metadata-authenticated workloads, like GKE WorkloadIdentity or GCE Instance metadata auth
- Added a secondary fallback signer to StorageJSON
- Refactored the signing process a bit to simplify logic and provide a more user-friendly experience in case of issues
- Added `google-cloud-env` support to the shared initialise so all modules can use it
Fixes #502
=> [StorageJSON] Add fallback URL signing mechanism via IAM SignBlob API

lib/fog/storage/google_xml/models/file.rb, test/unit/storage/test_common_xml_collections.rb
Previously if a file were created with NULL bytes, `File#save` would
fail because the raw body was being set in the header. We now only allow
metadata that starts with `x-goog-meta-` to be passed in as custom
headers.
Closes #507
=> Fix GoogleXML::File#save incorrectly passing body to headers

ci/docker-image/Dockerfile
Primary purpose of the upgrade is newer ruby since 2.3 is EOL which is causing issues on #509 
This will force 2.5 to be installed which is enough for our integration pipeline purposes.
TravisCI will still continue to run all non-EOL'ed rubies so we should see compatibility issues if they arise.
=> Upgrade CI docker image to Ubuntu 18.04

.travis.yml, README.md, fog-google.gemspec, lib/fog/compute/google/requests/insert_server.rb, lib/fog/google/requests/sql/delete_user.rb
google-api-client support `shielded_instance_config` since 0.44.2
googleapis/google-api-ruby-client@9678faba19830db0671870acca86794fbc83cb42
It is used to create GCE instances with "Shielded VM" feature
https://cloud.google.com/security/shielded-cloud/shielded-vm
=> Make insert_server support ShieldedInstanceConfig

lib/fog/storage/google_json/requests/copy_object.rb, test/integration/storage/test_objects.rb
For example: passing `destination_predefined_acl`
handles: https://github.com/fog/fog-google/issues/505 and https://github.com/fog/fog-google/pull/499#issuecomment-736986810
=> copy_object: support passing another request options

README.md
It really sucks that we have to do this but I see no other way rather than ask for help. I also realise that this org is not owned by us so before I put the notice up I want @plribeiro3000 and @geemus to take a look and see if you folks are ok with such a public plea.
Thank you.
CC @icco
=> Update README.md with CI issues notice

lib/fog/google/shared.rb, lib/fog/storage/google_json/models/directories.rb, lib/fog/storage/google_json/models/directory.rb, lib/fog/storage/google_json/models/file.rb, lib/fog/storage/google_json/models/files.rb, lib/fog/storage/google_json/requests/get_object.rb, lib/fog/storage/google_json/requests/list_buckets.rb, lib/fog/storage/google_json/requests/list_objects.rb, lib/fog/storage/google_json/requests/put_bucket.rb, lib/fog/storage/google_json/requests/put_bucket_acl.rb, lib/fog/storage/google_json/requests/put_object.rb, lib/fog/storage/google_json/requests/put_object_acl.rb, lib/fog/storage/google_xml/models/file.rb
This makes `bundle exec rake test:storage` pass for both Ruby 2.7.2 and
3.0.0.
```
TestStorageRequests
test_directories_destroy                                        PASS (2.16s)
test_directories_put                                            PASS (0.71s)
test_put_object_predefined_acl                                  PASS (1.51s)
test_delete_object                                              PASS (1.73s)
test_directory_files                                            PASS (1.80s)
test_list_object_acl                                            PASS (1.46s)
test_directory_public_url                                       PASS (0.84s)
test_put_object_contradictory_content_type                      PASS (1.61s)
test_object_metadata                                            PASS (1.65s) …
```
=> Fix Ruby 3.0 kwargs failures

lib/fog/storage/google_json/requests/copy_object.rb, test/integration/storage/test_objects.rb
This PR adds ability to pass [object properties](https://cloud.google.com/storage/docs/json_api/v1/objects?hl=en#resource) like `content_type` on copying Storage objects. At the same time, it also fixes the issue with request_options not being passed properly and having no effect, while taking care of the change in #513 to work as before.
This is needed to fix carrierwaveuploader/carrierwave#2533.
=> Support passing object properties to #copy_object

lib/fog/google/shared.rb, lib/fog/storage/google_json/models/directories.rb, lib/fog/storage/google_json/models/directory.rb, lib/fog/storage/google_json/models/file.rb, lib/fog/storage/google_json/models/files.rb, lib/fog/storage/google_json/requests/get_object.rb, lib/fog/storage/google_json/requests/list_buckets.rb, lib/fog/storage/google_json/requests/list_objects.rb, lib/fog/storage/google_json/requests/put_bucket.rb, lib/fog/storage/google_json/requests/put_bucket_acl.rb, lib/fog/storage/google_json/requests/put_object.rb, lib/fog/storage/google_json/requests/put_object_acl.rb, lib/fog/storage/google_xml/models/file.rb
In case the download is terminated, it's best to have unlinked the file
to avoid large files lingering. Since we're passing in an IO buffer
instead of a path, we need to seek to the beginning of the file in order
to read from it.
=> Unlink file temp file immediately

lib/fog/storage/google_json/requests/copy_object.rb
refs: https://github.com/fog/fog-google/commit/08fe0c9ec966e26e9760f01466a7f108bbb7d770#diff-0ff494c60559cd861720e6b0c68e4142e68b5b72a3f962eb6e17d5f432ba756aR18
Focusing on `#copy_object` related tests, they passes on both Ruby 2.7.3 and 3.0.1
```
% bundle exec rake test TEST=test/integration/storage/test_objects.rb
Started with run options --seed 30880
TestStorageRequests
test_copy_object_with_request_options                           PASS (2.30s)
test_copy_object_predefined_acl                                 PASS (1.02s)
test_copy_object                                                PASS (0.85s)
test_copy_object_with_object_property                           PASS (0.88s)
Finished in 5.04669s
4 tests, 4 assertions, 0 failures, 0 errors, 0 skips
```
=> Fix Ruby 3.0 kwargs error in `#copy_object`

lib/fog/storage/google_json/utils.rb, test/unit/storage/test_json_requests.rb
After updating the gem to v1.13.0, I noticed a minor regression introduced in https://github.com/fog/fog-google/pull/517,  which broke using Paperclip for us. The reason being, that `.gsub("%2F", "/")` is not done after the code that replaces the deprecated `URI.encode` method. 
The code that replaces `URI.encode` does return `%2` instead of `/`.
`'a/b/c'.b.gsub(/([^a-zA-Z0-9_.\-~]+)/) { |m| '%' + m.unpack('H2' * m.bytesize).join('%').upcase }` returns `a%2Fb%2Fc`
The in the [PR](https://github.com/fog/fog-google/pull/517) mentioned [addressable gem](https://github.com/sporkmonger/addressable) also does not:
`Addressable::URI.encode_component('a/b/c', Addressable::URI::CharacterClasses::PATH)` returns `a/b/c`
This PR just adds back `.gsub("%2F", "/")` to fix the regression.
=> Unescape slashes in urls

lib/fog/storage/google_json/requests/get_object.rb, test/integration/storage/storage_shared.rb, test/integration/storage/test_objects.rb
The change in #521 caused the `Tempfile` buffer to be used, which opens
a file in ASCII mode by default. We need to make use of `binmode` to
activate binary streams.
Closes https://github.com/fog/fog-google/issues/533
=> Fix get_object not working with binary files

lib/fog/storage/google_json/models/file.rb
Previously the response body would be loaded twice in memory whenever
`GoogleJSON::File#body` was called. This was happening because inside
the ternary condition, `file.body` was recursively calling itself twice
even though the body was already loaded. We rewrite this method to be
simpler and to have a proper base condition.
Closes https://github.com/fog/fog-google/issues/541
=> Avoid duplicate GET requests when retrieving body

lib/fog/storage/google_json/models/files.rb
we should take "page_next_token" into account while listing pages through `#files`
this reproduces the behaviour we have with GoogleXML files collection
I guess that this should fix known issue #42
Example of usage:
```ruby
connection =
::Fog::Storage.new(
provider:               'Google',
google_project:        '...',
google_json_key_string: '...'
)
bucket_name = '...'
directory = connection.directories.get(bucket_name)
files = directory.files.each_with_object([]) { |file, results| results << file }
files.size # can now be greater than 1000
```
=> ensure to retrieve all pages when using #files with given block

fog-google.gemspec
This is an alternative to https://github.com/fog/fog-google/pull/422, in order to get newer versions of fog-core to enable compatibility with other fog provider gems.  
Looking into the history, it looks like a similar change was reverted: https://github.com/fog/fog-google/pull/419 https://github.com/fog/fog-google/pull/487
There is talk of a regression, but all unit tests pass and as far as I can tell the only issue is the deprecation warnings.
It's been years since talk doing the update 'properly' and https://github.com/fog/fog-google/pull/422 seems to be stuck in limbo.  At this point this gem lagging behind fog-core and other provider gems is no longer a minor inconvenience--it is blocking us from getting new features in other provider gems and from upgrading to Ruby 3.  
We would …
=> Allow bumping fog-core

.github/workflows/integration.yml, .github/workflows/unit.yml
This PR adds Ruby 3.1 to the CI matrix for all spec runs.
The unit tests ran green on my fork, but the integration tests didn't run at all.  So there may be failures in the integration specs that need to be resolved.
=> Add Ruby 3.1 to the CI matrix

test/integration/monitoring/test_timeseries.rb
Good news: Google Monitoring stopped spewing ClientErrors on retrieving metrics where none exist.
Bad news: Our wait  logic no longer works.  
Changed up the retry method with Fog.wait_for - this should fix it.
=> Change to Fog.wait_for in monitoring tests

.github/workflows/integration-sql.yml, .github/workflows/integration.yml
Starting with separating SQL integration tests into their own job as that allows us to only trigger it on PR's where the code or deps have actually changed.
=> Attempt to make integration tests lighter

test/integration/monitoring/test_timeseries.rb
Add a retry to create_timeseries in one more place as the backend performs poorly in our integration scenarios
=> Fix one more flaky monitoring test

lib/fog/storage/google_json/real.rb
As of today we creating new `OpenSSL::PKey::RSA` when we sign, even if the existing `signing_key` is already a `OpenSSL::PKey::RSA`.
In google ruby gem they are doing the same approach - https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-storage/lib/google/cloud/storage/file/signer_v2.rb#L137
```
Warming up --------------------------------------
sign   119.000  i/100ms
new   179.000  i/100ms
Calculating -------------------------------------
sign      1.199k (± 0.7%) i/s -      6.069k in   5.063095s
new      1.791k (± 0.6%) i/s -      9.129k in   5.096376s
Comparison:
new:     1791.3 i/s
sign:     1198.7 i/s - 1.49x  slower
```
source: https://gist.github.com/yosiat/372bc468d23c568cd8722af7f56a2b03
=> improve perf for default_signer: Don't create new PKey::RSA if we already can sign

.github/workflows/integration-compute-core.yml, .github/workflows/integration-compute-instance_groups.yml, .github/workflows/integration-compute-loadbalancing.yml, .github/workflows/integration-compute-networking.yml, .github/workflows/integration-monitoring.yml, .github/workflows/integration-pubsub.yml, .github/workflows/integration-sql.yml, .github/workflows/integration-storage.yml
`bundler` is already set up as a part of `setup-ruby` workflow when caching gems so it's no longer necessary to call it separately.
=> Remove unnecessary workflow stage

fog-google.gemspec
Currently the google-cloud-storage gem has a version requirement of `google-apis-storage_v1 ~> 0.19.0`, which makes it impossible to install the latest fog-google since fog-google has a dependency of `~> 0.20.0`.
=> Relax google-apis-storage_v1 dependency

.github/workflows/unit.yml
To fix the recently failing `unit` workflows.
=> Remove deprecated ruby versions from unit tests

lib/fog/storage/google_json/models/file.rb
The following provides a way to ignore `predefined_acl` when fog-google is used within another gem that invokes `public=` (e.g. paperclip) without the user explicitly setting it.
=> Add uniform attr to inserting file

lib/fog/compute/google/models/servers.rb
If there are more instances than will fit in a page a next_page_token is returned.  This has to be passed in to subsequent calls in order to retrieve the full list of servers.
Note: I think this method could use some refactoring but I wanted to model this after the way `Snapshots#all` was fixed for consistency and change as little as possible for a targeted bug fix.
Fixes https://github.com/fog/fog-google/issues/607
=> Fix `Fog::Compute::Google::Servers#all` paging

test/helpers/integration_test_helper.rb, test/unit/compute/test_common_collections.rb, test/unit/compute/test_common_models.rb, test/unit/compute/test_server.rb, test/unit/dns/test_common_collections.rb, test/unit/monitoring/test_comon_collections.rb, test/unit/pubsub/test_common_collections.rb, test/unit/sql/test_common_collections.rb, test/unit/storage/test_common_json_collections.rb, test/unit/storage/test_common_xml_collections.rb, test/unit/storage/test_json_requests.rb, test/unit/storage/test_xml_requests.rb
In this pull request, we fixed the CI build.
```sh
uninitialized constant MiniTest (NameError)
Did you mean?  Minitest
```
=> Use `Minitest::Test` instead of `MiniTest::Test`

examples/create_instance_and_attach_disk_later.rb, lib/fog/compute/google/models/disks.rb, lib/fog/compute/google/models/server.rb, test/integration/compute/core_compute/test_servers.rb, test/unit/compute/test_disk.rb
As a new fog-google user, I encountered various issues in dynamically attaching and detaching disks against a running server, namely:
* https://github.com/fog/fog-google/issues/611
* https://github.com/fog/fog-google/issues/612
* Error when running under Ruby 3.x: `ArgumentError: wrong number of arguments (given 2, expected 1)`
* No example that demonstrates usage how to attach and detach disks against a running server
=> Spruce up attaching and detaching disks on running servers

.github/workflows/integration-compute-core.yml, .github/workflows/integration-compute-instance_groups.yml, .github/workflows/integration-compute-loadbalancing.yml, .github/workflows/integration-compute-networking.yml, .github/workflows/integration-monitoring.yml, .github/workflows/integration-pubsub.yml, .github/workflows/integration-sql.yml, .github/workflows/integration-storage.yml, .github/workflows/unit.yml, README.md
Ruby 2 has been long EOL so deprecating it as per our support policy: https://github.com/fog/fog-google#supported-ruby-versions
=> Deprecate Ruby-2.0 support

.github/workflows/integration-compute-core.yml, .github/workflows/integration-compute-instance_groups.yml, .github/workflows/integration-compute-loadbalancing.yml, .github/workflows/integration-compute-networking.yml, .github/workflows/integration-monitoring.yml, .github/workflows/integration-pubsub.yml, .github/workflows/integration-sql.yml, .github/workflows/integration-storage.yml
The old `self-hosted` setup has proven to be very flaky. Transitioning to the new ARC setup, see: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller
=> Migrate the Integration tests to new ARC runners

.github/workflows/integration-compute-core.yml, .github/workflows/integration-compute-instance_groups.yml, .github/workflows/integration-compute-loadbalancing.yml, .github/workflows/integration-compute-networking.yml, .github/workflows/integration-monitoring.yml, .github/workflows/integration-pubsub.yml, .github/workflows/integration-sql.yml, .github/workflows/integration-storage.yml, .github/workflows/unit.yml
- Add concurrency groups to integration tests to stop cleanup routines from stepping over each other.
- Add concurrency group to unit tests to cancel the runs if we updated the PR ref
- Trigger workflows when they get updated so we can test workflow changes inside the PRs
=> Add concurrency groups

lib/fog/compute/google/models/server.rb, lib/fog/compute/google/requests/stop_server.rb, test/integration/compute/core_compute/test_servers.rb
Stopping an instance with local SSD throws this error:
```
badRequest: VM has a Local SSD attached but an undefined value for `discard-local-ssd`. If using gcloud, please add `--discard-local-ssd=false` or `--discard-local-ssd=true` to your command.
```
The Google API `Google::Apis::Compute::stop_instance` (in [service.rb](https://github.com/googleapis/google-api-ruby-client/blob/main/generated/google-apis-compute_v1/lib/google/apis/compute_v1/service.rb)) supports a keyword argument `discard_local_ssd`, but fog-google does not. This PR adds an optional argument to allow assigning a value when stopping an instance. The default is false, both to mimic Google default, and to preserve backward compatibility with existing fog-google users.
To stop an instance containing local SSD:
```
async = …
```
=> Add support for discard_local_ssd when stopping an instance

lib/fog/google/shared.rb, lib/fog/storage/google_json.rb, lib/fog/storage/google_json/real.rb
Previously when a service account attempted to use the IAM SignBlob API, the request would fail with a 403
`ACCESS_TOKEN_SCOPE_INSUFFICIENT` because the wrong scope was requested.
As documented in
https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/signBlob, either `https://www.googleapis.com/auth/iam` or
`https://www.googleapis.com/auth/cloud-platform` is needed.
This commit fixes an issue where the default authorization header with the `https://www.googleapis.com/auth/devstorage.full_control` scope was being used by the IAM service. This occurred because the previous code did not actually set the scope properly, and for the IAM service to work properly, we need to request a new access token with the correct scope.
Note that the service account in …
=> storage: fix incorrect API scopes for IAM SignBlob API
